services:
  app:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php_container
    volumes:
      - ./app_super_gestao:/var/www/app_super_gestao
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: mysql.dockerfile
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sg
    ports:
      - "33067:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: